#!/bin/bash
# SessionStart hook for Fast Launch — Auto-gen-content
#
# - Materialises posting credentials from env vars into .env (gitignored).
# - Installs npm deps so render scripts (node-canvas) and posting scripts work.
#
# Only runs in Claude Code on the web. Local dev is unaffected.

set -euo pipefail

if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

cd "${CLAUDE_PROJECT_DIR:-$(dirname "$(dirname "$(dirname "$(readlink -f "$0")")")")}"

# ── 1. Materialise .env from session env vars ────────────────────────────────
# Each var is written only if set in the environment. .env is gitignored.
SECRETS=(
  LINKEDIN_ACCESS_TOKEN
  LINKEDIN_MEMBER_URN
  LINKEDIN_CLIENT_ID
  LINKEDIN_CLIENT_SECRET
  INSTAGRAM_ACCESS_TOKEN
  INSTAGRAM_ACCESS_TOKEN_SHORT
  INSTAGRAM_BUSINESS_ACCOUNT_ID
  INSTAGRAM_USERNAME
  META_APP_ID
  META_APP_SECRET
)

ENV_FILE=".env"
TMP_FILE=".env.tmp.$$"
: > "$TMP_FILE"
echo "# Auto-generated by .claude/hooks/session-start.sh — do not edit by hand" >> "$TMP_FILE"
echo "# Sourced from session env vars at session start." >> "$TMP_FILE"

written=0
missing=()
for key in "${SECRETS[@]}"; do
  val="${!key:-}"
  if [ -n "$val" ]; then
    # Escape any literal $ in the value so dotenv doesn't try to expand it.
    printf '%s=%s\n' "$key" "$val" >> "$TMP_FILE"
    written=$((written + 1))
  else
    missing+=("$key")
  fi
done

mv "$TMP_FILE" "$ENV_FILE"
chmod 600 "$ENV_FILE"

echo "[session-start] wrote $written secret(s) to .env"
if [ ${#missing[@]} -gt 0 ]; then
  echo "[session-start] missing env vars (set as session secrets in the dashboard if you need them):"
  for k in "${missing[@]}"; do echo "  - $k"; done
fi

# ── 2. Install npm deps ──────────────────────────────────────────────────────
# `npm install` is preferred over `ci` so the cached container layer is reused
# across sessions. node-canvas pulls prebuilt binaries via prebuild-install.
if [ -f package.json ]; then
  echo "[session-start] npm install..."
  npm install --no-audit --no-fund --loglevel=error
fi

echo "[session-start] done"
